version: '3.1'
services:
  broj-service:
    container_name: broj-service
    image: broj-service
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_DB=broj-db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres